
package komca.fi.tac;
import java.sql.*;
import java.util.*;
import WIZ.FR.COM.*;
import WIZ.FR.DAO.*;
import WIZ.FR.MSG.*;
import WIZ.FR.UTIL.*;
public class tac10_r17
{
    public tac10_r17()
    {
    }
    //##**$$searchTest
    /* * 프로그램명 : tac10_r17
    * 작성자 : 손주환
    * 작성일 : 2009/11/27
    * 설명 :
    * 수정일1:
    * 수정자 :
    * 수정내용 :
    */
    public DOBJ CTLsearchTest(DOBJ dobj)
    {
        WizUtil wutil = new WizUtil(dobj);
        Connection Conn = null;
        try
        {
            Connector connection = new Connector();
            Conn = connection.getConnection("PFDB",dobj);
        }
        catch(Exception e)
        {
            dobj.setRetmsg(e,"DataBase Connection Error");
            e.printStackTrace();
            return dobj;
        }
        try
        {
            dobj  = CALLsearchTest_SEL1(Conn, dobj);           //  분배내역서(매체+공제+타이틀)
        }
        catch(Exception e)
        {
            e.printStackTrace();
            try
            {
                dobj.setRtncode(-1);
                dobj.setRetmsg(e.getMessage());
            }
            catch(Exception re)
            {
                re.printStackTrace();
            }
        }
        finally
        {
            try
            {
                Conn.close();
            }
            catch(SQLException e)
            {
                dobj.setRtncode(-1);
                dobj.setRetmsg(e,"DataBase Close Error");
                e.printStackTrace();
            }
        }
        return dobj;
    }
    public DOBJ CTLsearchTest( DOBJ dobj, Object Connx) throws Exception
    {
        WizUtil wutil = new WizUtil(dobj);
        Connection Conn = (Connection)Connx;
        dobj  = CALLsearchTest_SEL1(Conn, dobj);           //  분배내역서(매체+공제+타이틀)
        return dobj;
    }
    // 분배내역서(매체+공제+타이틀)
    public DOBJ CALLsearchTest_SEL1(Connection Conn, DOBJ dobj) throws Exception
    {
        WizUtil wutil = new WizUtil(dobj);
        dobj.setRtnname("SEL1");
        QExecutor qexe = new QExecutor(dobj);
        dobj.setRtnname("SEL1");
        VOBJ dvobj = dobj.getRetObject("S");           //사용자 화면에서 발생한 Object입니다.
        SQLObject  sobj = SQLsearchTest_SEL1(dobj, dvobj);
        VOBJ rvobj = qexe.executeQuery(Conn, sobj);
        rvobj.setName("SEL1");
        rvobj.Println("SEL1");
        dobj.setRetObject(rvobj);
        return dobj;
    }
    private SQLObject SQLsearchTest_SEL1(DOBJ dobj, VOBJ dvobj) throws Exception
    {
        WizUtil wutil = new WizUtil(dobj);
        String   SUPP_YRMN = dobj.getRetObject("S").getRecord().get("SUPP_YRMN");   //지급 년월
        SQLObject sobj = new SQLObject();
        String    query="";
        query +=" SELECT  C.TRNSF_NM,  C.CNT  ||  '건'  CNT,  C.DISTR_AMT1  AS  DISTR_AMT1,  C.DISTR_AMT2  AS  DISTR_AMT2,  C.DISTR_AMT3  AS  DISTR_AMT3,  C.DISTR_AMT4  AS  DISTR_AMT4,  C.DISTR_AMT5  AS  DISTR_AMT5,  C.DISTR_AMT6  AS  DISTR_AMT6,  C.DISTR_AMT7  AS  DISTR_AMT7,  C.DISTR_AMT8  AS  DISTR_AMT8,  C.DISTR_AMT9  AS  DISTR_AMT9,  C.DISTR_AMT10  AS  DISTR_AMT10,  C.DISTR_AMT11  AS  DISTR_AMT11,  C.DISTR_AMT12  AS  DISTR_AMT12,  C.DISTR_AMT13  AS  DISTR_AMT13,  C.DISTR_AMT14  AS  DISTR_AMT14,  C.DISTR_AMT15  AS  DISTR_AMT15,  C.DISTR_AMT16  AS  DISTR_AMT16,  C.DISTR_AMT17  AS  DISTR_AMT17,  C.DISTR_AMT18  AS  DISTR_AMT18,  C.DISTR_AMT19  AS  DISTR_AMT19,  C.DISTR_AMT20  AS  DISTR_AMT20,  C.DISTR_AMT21  AS  DISTR_AMT21,  C.DISTR_AMT22  AS  DISTR_AMT22,  C.DISTR_AMT23  AS  DISTR_AMT23,  C.DISTR_AMT24  AS  DISTR_AMT24,  C.DISTR_AMT25  AS  DISTR_AMT25,  C.DISTR_AMT26  AS  DISTR_AMT26,  C.DISTR_AMT27  AS  DISTR_AMT27,  C.DISTR_TOT  AS  DISTR_TOT,  D.DISTR_AMT28  AS  DISTR_AMT28,  D.DISTR_AMT29  AS  DISTR_AMT29,  D.DISTR_AMT30  AS  DISTR_AMT30,  C.ATAX_AMT  AS  DISTR_AMT31,  C.ATAX_AMT1  AS  ATAX_AMT,  D.DISTR_AMT32  AS  DISTR_AMT32,  D.DISTR_AMT33  AS  DISTR_AMT33,  D.DISTR_AMT34  AS  DISTR_AMT34,  D.DISTR_AMT35  AS  DISTR_AMT35,  D.DISTR_AMT36  AS  DISTR_AMT36,  D.DISTR_AMT37  AS  DISTR_AMT37,  D.DISTR_AMT38  AS  DISTR_AMT38,  D.DISTR_AMT39  AS  DISTR_AMT39,  D.DISTR_AMT40  AS  DISTR_AMT40,  D.DISTR_AMT41  AS  DISTR_AMT41,  D.DISTR_AMT42  AS  DISTR_AMT42,  D.DISTR_AMT43  AS  DISTR_AMT43,  D.DISTR_AMT44  AS  DISTR_AMT44,  D.DISTR_AMT45  AS  DISTR_AMT45,  D.DISTR_AMT46  AS  DISTR_AMT46,  D.DISTR_AMT45  AS  DISTR_AMT47,  D.DISTR_GTOT,  (NVL(C.DISTR_TOT,0)  -  NVL(D.DISTR_GTOT,0)  +  NVL(C.ATAX_AMT1,0))  AS  DISTR_STOT,  E.DISTR_TAMT1  AS  DISTR_TAMT1  ,  E.DISTR_TAMT2  AS  DISTR_TAMT2  ,  E.DISTR_TAMT3  AS  DISTR_TAMT3  ,  E.DISTR_TAMT4  AS  DISTR_TAMT4  ,  E.DISTR_TAMT5  AS  DISTR_TAMT5  ,  E.DISTR_TAMT6  AS  DISTR_TAMT6  ,  E.DISTR_TAMT7  AS  DISTR_TAMT7  ,  E.DISTR_TAMT8  AS  DISTR_TAMT8  ,  E.DISTR_TAMT9  AS  DISTR_TAMT9  ,  E.DISTR_TAMT10  AS  DISTR_TAMT10,  E.DISTR_TAMT11  AS  DISTR_TAMT11,  E.DISTR_TAMT12  AS  DISTR_TAMT12,  E.DISTR_TAMT13  AS  DISTR_TAMT13,  E.DISTR_TAMT14  AS  DISTR_TAMT14,  E.DISTR_TAMT15  AS  DISTR_TAMT15,  E.DISTR_TAMT16  AS  DISTR_TAMT16,  E.DISTR_TAMT17  AS  DISTR_TAMT17,  E.DISTR_TAMT18  AS  DISTR_TAMT18,  E.DISTR_TAMT19  AS  DISTR_TAMT19,  E.DISTR_TAMT20  AS  DISTR_TAMT20,  E.DISTR_TAMT21  AS  DISTR_TAMT21,  E.DISTR_TAMT22  AS  DISTR_TAMT22,  E.DISTR_TAMT23  AS  DISTR_TAMT23,  E.DISTR_TAMT24  AS  DISTR_TAMT24,  E.DISTR_TAMT25  AS  DISTR_TAMT25,  E.DISTR_TAMT26  AS  DISTR_TAMT26,  E.DISTR_TAMT27  AS  DISTR_TAMT27,  F.DISTR_TAMT28  AS  DISTR_TAMT28,  F.DISTR_TAMT29  AS  DISTR_TAMT29,  F.DISTR_TAMT30  AS  DISTR_TAMT30,  F.DISTR_TAMT31  AS  DISTR_TAMT31,  F.DISTR_TAMT32  AS  DISTR_TAMT32,  F.DISTR_TAMT33  AS  DISTR_TAMT33,  F.DISTR_TAMT34  AS  DISTR_TAMT34,  F.DISTR_TAMT35  AS  DISTR_TAMT35,  F.DISTR_TAMT36  AS  DISTR_TAMT36,  F.DISTR_TAMT37  AS  DISTR_TAMT37,  F.DISTR_TAMT38  AS  DISTR_TAMT38,  F.DISTR_TAMT39  AS  DISTR_TAMT39,  F.DISTR_TAMT40  AS  DISTR_TAMT40,  F.DISTR_TAMT41  AS  DISTR_TAMT41,  F.DISTR_TAMT42  AS  DISTR_TAMT42,  F.DISTR_TAMT43  AS  DISTR_TAMT43,  F.DISTR_TAMT44  AS  DISTR_TAMT44,  F.DISTR_TAMT45  AS  DISTR_TAMT45,  F.DISTR_TAMT46  AS  DISTR_TAMT46  FROM  (   \n";
        query +=" SELECT  Z.TRNSF_GBN,  Z.TRNSF_NM,  MAX(Z.CNT)  CNT,  SUM(Z.DISTR_AMT1)  AS  DISTR_AMT1,  SUM(Z.DISTR_AMT2)  AS  DISTR_AMT2,  SUM(Z.DISTR_AMT3)  AS  DISTR_AMT3,  SUM(Z.DISTR_AMT4)  AS  DISTR_AMT4,  SUM(Z.DISTR_AMT5)  AS  DISTR_AMT5,  SUM(Z.DISTR_AMT6)  AS  DISTR_AMT6,  SUM(Z.DISTR_AMT7)  AS  DISTR_AMT7,  SUM(Z.DISTR_AMT8)  AS  DISTR_AMT8,  SUM(Z.DISTR_AMT9)  AS  DISTR_AMT9,  SUM(Z.DISTR_AMT10)  AS  DISTR_AMT10,  SUM(Z.DISTR_AMT11)  AS  DISTR_AMT11,  SUM(Z.DISTR_AMT12)  AS  DISTR_AMT12,  SUM(Z.DISTR_AMT13)  AS  DISTR_AMT13,  SUM(Z.DISTR_AMT14)  AS  DISTR_AMT14,  SUM(Z.DISTR_AMT15)  AS  DISTR_AMT15,  SUM(Z.DISTR_AMT16)  AS  DISTR_AMT16,  SUM(Z.DISTR_AMT17)  AS  DISTR_AMT17,  SUM(Z.DISTR_AMT18)  AS  DISTR_AMT18,  SUM(Z.DISTR_AMT19)  AS  DISTR_AMT19,  SUM(Z.DISTR_AMT20)  AS  DISTR_AMT20,  SUM(Z.DISTR_AMT21)  AS  DISTR_AMT21,  SUM(Z.DISTR_AMT22)  AS  DISTR_AMT22,  SUM(Z.DISTR_AMT23)  AS  DISTR_AMT23,  SUM(Z.DISTR_AMT24)  AS  DISTR_AMT24,  SUM(Z.DISTR_AMT25)  AS  DISTR_AMT25,  SUM(Z.DISTR_AMT26)  AS  DISTR_AMT26,  SUM(Z.DISTR_AMT27)  AS  DISTR_AMT27,  SUM(Z.ATAX_AMT)  AS  ATAX_AMT,  MAX(Z.ATAX_AMT1)  AS  ATAX_AMT1,  MAX(Z.DISTR_TOT)  AS  DISTR_TOT  FROM  (   \n";
        query +=" SELECT  A.TRNSF_GBN,  '원작'  AS  TRNSF_NM,   \n";
        query +=" (SELECT  COUNT(R.MB_CD)  AS  CNT  FROM  (   \n";
        query +=" SELECT  DISTINCT(A.MB_CD)  AS  MB_CD  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  A,  FIDU.TENV_AVECLASSCD  B  ,FIDU.TMEM_MB  C  WHERE  A.MB_CD  =  C.MB_CD(+)   \n";
        query +=" AND  SUBSTR(A.MDM_CD,1,2)  =  B.AVECLASS_CD   \n";
        query +=" AND  A.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  A.TRNSF_GBN  =  '1'   \n";
        query +=" AND  C.MB_GBN1  =  'W'   \n";
        query +=" AND  (C.HOUSE_CD  IS  NULL   \n";
        query +=" OR  C.HOUSE_CD  ='082')  )  R  )  AS  CNT,  DECODE(B.PRNT_SEQ,  '1',  SUM(A.ORGDISTR_AMT))  DISTR_AMT1,  DECODE(B.PRNT_SEQ,  '2',  SUM(A.ORGDISTR_AMT))  DISTR_AMT2,  DECODE(B.PRNT_SEQ,  '3',  SUM(A.ORGDISTR_AMT))  DISTR_AMT3,  DECODE(B.PRNT_SEQ,  '4',  SUM(A.ORGDISTR_AMT))  DISTR_AMT4,  DECODE(B.PRNT_SEQ,  '5',  SUM(A.ORGDISTR_AMT))  DISTR_AMT5,  DECODE(B.PRNT_SEQ,  '6',  SUM(A.ORGDISTR_AMT))  DISTR_AMT6,  DECODE(B.PRNT_SEQ,  '7',  SUM(A.ORGDISTR_AMT))  DISTR_AMT7,  DECODE(B.PRNT_SEQ,  '8',  SUM(A.ORGDISTR_AMT))  DISTR_AMT8,  DECODE(B.PRNT_SEQ,  '9',  SUM(A.ORGDISTR_AMT))  DISTR_AMT9,  DECODE(B.PRNT_SEQ,  '10',  SUM(A.ORGDISTR_AMT))  DISTR_AMT10,  DECODE(B.PRNT_SEQ,  '11',  SUM(A.ORGDISTR_AMT))  DISTR_AMT11,  DECODE(B.PRNT_SEQ,  '12',  SUM(A.ORGDISTR_AMT))  DISTR_AMT12,  DECODE(B.PRNT_SEQ,  '13',  SUM(A.ORGDISTR_AMT))  DISTR_AMT13,  DECODE(B.PRNT_SEQ,  '14',  SUM(A.ORGDISTR_AMT))  DISTR_AMT14,  DECODE(B.PRNT_SEQ,  '15',  SUM(A.ORGDISTR_AMT))  DISTR_AMT15,  DECODE(B.PRNT_SEQ,  '16',  SUM(A.ORGDISTR_AMT))  DISTR_AMT16,  DECODE(B.PRNT_SEQ,  '17',  SUM(A.ORGDISTR_AMT))  DISTR_AMT17,  DECODE(B.PRNT_SEQ,  '18',  SUM(A.ORGDISTR_AMT))  DISTR_AMT18,  DECODE(B.PRNT_SEQ,  '19',  SUM(A.ORGDISTR_AMT))  DISTR_AMT19,  DECODE(B.PRNT_SEQ,  '20',  SUM(A.ORGDISTR_AMT))  DISTR_AMT20,  DECODE(B.PRNT_SEQ,  '21',  SUM(A.ORGDISTR_AMT))  DISTR_AMT21,  DECODE(B.PRNT_SEQ,  '22',  SUM(A.ORGDISTR_AMT))  DISTR_AMT22,  DECODE(B.PRNT_SEQ,  '23',  SUM(A.ORGDISTR_AMT))  DISTR_AMT23,  DECODE(B.PRNT_SEQ,  '24',  SUM(A.ORGDISTR_AMT))  DISTR_AMT24,  DECODE(B.PRNT_SEQ,  '25',  SUM(A.ORGDISTR_AMT))  DISTR_AMT25,  DECODE(B.PRNT_SEQ,  '26',  SUM(A.ORGDISTR_AMT))  DISTR_AMT26,  DECODE(B.PRNT_SEQ,  '27',  SUM(A.ORGDISTR_AMT))  DISTR_AMT27,  SUM(A.ATAX_AMT)  AS  ATAX_AMT,   \n";
        query +=" (SELECT  SUM(X.ORGDISTR_AMT)  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  X  ,FIDU.TMEM_MB  Z  WHERE  X.MB_CD  =  Z.MB_CD(+)   \n";
        query +=" AND  X.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  X.TRNSF_GBN  =A.TRNSF_GBN   \n";
        query +=" AND  Z.MB_GBN1  =  'W'   \n";
        query +=" AND  (Z.HOUSE_CD  IS  NULL   \n";
        query +=" OR  Z.HOUSE_CD  ='082')  )  AS  DISTR_TOT,  0  ATAX_AMT1  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  A,  FIDU.TENV_AVECLASSCD  B  ,FIDU.TMEM_MB  C  WHERE  A.MB_CD  =  C.MB_CD(+)   \n";
        query +=" AND  SUBSTR(A.MDM_CD,1,2)  =  B.AVECLASS_CD   \n";
        query +=" AND  A.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  A.TRNSF_GBN  =  '1'   \n";
        query +=" AND  C.MB_GBN1  =  'W'   \n";
        query +=" AND  (C.HOUSE_CD  IS  NULL   \n";
        query +=" OR  C.HOUSE_CD  ='082')  GROUP  BY  A.TRNSF_GBN,  B.PRNT_SEQ  UNION  ALL   \n";
        query +=" SELECT  A.TRNSF_GBN,  '승계.양수'  AS  TRNSF_NM,   \n";
        query +=" (SELECT  COUNT(R.MB_CD)  AS  CNT  FROM  (   \n";
        query +=" SELECT  DISTINCT(A.MB_CD)  AS  MB_CD  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  A,  FIDU.TENV_AVECLASSCD  B  ,FIDU.TMEM_MB  C  WHERE  A.MB_CD  =  C.MB_CD(+)   \n";
        query +=" AND  SUBSTR(A.MDM_CD,1,2)  =  B.AVECLASS_CD   \n";
        query +=" AND  A.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  A.TRNSF_GBN  =  '2'   \n";
        query +=" AND  C.MB_GBN1  =  'W'   \n";
        query +=" AND  (C.HOUSE_CD  IS  NULL   \n";
        query +=" OR  C.HOUSE_CD  ='082')  )  R  )  AS  CNT,  DECODE(B.PRNT_SEQ,  '1',  SUM(A.ORGDISTR_AMT))  DISTR_AMT1,  DECODE(B.PRNT_SEQ,  '2',  SUM(A.ORGDISTR_AMT))  DISTR_AMT2,  DECODE(B.PRNT_SEQ,  '3',  SUM(A.ORGDISTR_AMT))  DISTR_AMT3,  DECODE(B.PRNT_SEQ,  '4',  SUM(A.ORGDISTR_AMT))  DISTR_AMT4,  DECODE(B.PRNT_SEQ,  '5',  SUM(A.ORGDISTR_AMT))  DISTR_AMT5,  DECODE(B.PRNT_SEQ,  '6',  SUM(A.ORGDISTR_AMT))  DISTR_AMT6,  DECODE(B.PRNT_SEQ,  '7',  SUM(A.ORGDISTR_AMT))  DISTR_AMT7,  DECODE(B.PRNT_SEQ,  '8',  SUM(A.ORGDISTR_AMT))  DISTR_AMT8,  DECODE(B.PRNT_SEQ,  '9',  SUM(A.ORGDISTR_AMT))  DISTR_AMT9,  DECODE(B.PRNT_SEQ,  '10',  SUM(A.ORGDISTR_AMT))  DISTR_AMT10,  DECODE(B.PRNT_SEQ,  '11',  SUM(A.ORGDISTR_AMT))  DISTR_AMT11,  DECODE(B.PRNT_SEQ,  '12',  SUM(A.ORGDISTR_AMT))  DISTR_AMT12,  DECODE(B.PRNT_SEQ,  '13',  SUM(A.ORGDISTR_AMT))  DISTR_AMT13,  DECODE(B.PRNT_SEQ,  '14',  SUM(A.ORGDISTR_AMT))  DISTR_AMT14,  DECODE(B.PRNT_SEQ,  '15',  SUM(A.ORGDISTR_AMT))  DISTR_AMT15,  DECODE(B.PRNT_SEQ,  '16',  SUM(A.ORGDISTR_AMT))  DISTR_AMT16,  DECODE(B.PRNT_SEQ,  '17',  SUM(A.ORGDISTR_AMT))  DISTR_AMT17,  DECODE(B.PRNT_SEQ,  '18',  SUM(A.ORGDISTR_AMT))  DISTR_AMT18,  DECODE(B.PRNT_SEQ,  '19',  SUM(A.ORGDISTR_AMT))  DISTR_AMT19,  DECODE(B.PRNT_SEQ,  '20',  SUM(A.ORGDISTR_AMT))  DISTR_AMT20,  DECODE(B.PRNT_SEQ,  '21',  SUM(A.ORGDISTR_AMT))  DISTR_AMT21,  DECODE(B.PRNT_SEQ,  '22',  SUM(A.ORGDISTR_AMT))  DISTR_AMT22,  DECODE(B.PRNT_SEQ,  '23',  SUM(A.ORGDISTR_AMT))  DISTR_AMT23,  DECODE(B.PRNT_SEQ,  '24',  SUM(A.ORGDISTR_AMT))  DISTR_AMT24,  DECODE(B.PRNT_SEQ,  '25',  SUM(A.ORGDISTR_AMT))  DISTR_AMT25,  DECODE(B.PRNT_SEQ,  '26',  SUM(A.ORGDISTR_AMT))  DISTR_AMT26,  DECODE(B.PRNT_SEQ,  '27',  SUM(A.ORGDISTR_AMT))  DISTR_AMT27,  SUM(A.ATAX_AMT)  AS  ATAX_AMT,   \n";
        query +=" (SELECT  SUM(X.ORGDISTR_AMT)  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  X  ,FIDU.TMEM_MB  Y  WHERE  X.MB_CD  =  Y.MB_CD(+)   \n";
        query +=" AND  X.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  X.TRNSF_GBN  =  A.TRNSF_GBN   \n";
        query +=" AND  Y.MB_GBN1  =  'W'   \n";
        query +=" AND  (Y.HOUSE_CD  IS  NULL   \n";
        query +=" OR  Y.HOUSE_CD  ='082')  )  AS  DISTR_TOT,  0  ATAX_AMT1  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  A,  FIDU.TENV_AVECLASSCD  B  ,FIDU.TMEM_MB  C  WHERE  A.MB_CD  =  C.MB_CD(+)   \n";
        query +=" AND  SUBSTR(A.MDM_CD,1,2)  =  B.AVECLASS_CD   \n";
        query +=" AND  A.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  A.TRNSF_GBN  =  '2'   \n";
        query +=" AND  C.MB_GBN1  =  'W'   \n";
        query +=" AND  (C.HOUSE_CD  IS  NULL   \n";
        query +=" OR  C.HOUSE_CD  ='082')  GROUP  BY  A.TRNSF_GBN,  B.PRNT_SEQ  UNION  ALL   \n";
        query +=" SELECT  '3'  AS  TRNSF_GBN,  '외국'  AS  TRNSF_NM,   \n";
        query +=" (SELECT  COUNT(R.MB_CD)  AS  CNT  FROM  (   \n";
        query +=" SELECT  DISTINCT(A.MB_CD)  AS  MB_CD  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  A,  FIDU.TENV_AVECLASSCD  B  ,FIDU.TMEM_MB  C  WHERE  A.MB_CD  =  C.MB_CD(+)   \n";
        query +=" AND  SUBSTR(A.MDM_CD,1,2)  =  B.AVECLASS_CD   \n";
        query +=" AND  A.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  C.HOUSE_CD  IS  NOT  NULL   \n";
        query +=" AND  C.MB_GBN1  =  'W'   \n";
        query +=" AND  C.HOUSE_CD  <>  '082'  )  R  )  AS  CNT,  DECODE(B.PRNT_SEQ,  '1',  SUM(A.ORGDISTR_AMT))  DISTR_AMT1,  DECODE(B.PRNT_SEQ,  '2',  SUM(A.ORGDISTR_AMT))  DISTR_AMT2,  DECODE(B.PRNT_SEQ,  '3',  SUM(A.ORGDISTR_AMT))  DISTR_AMT3,  DECODE(B.PRNT_SEQ,  '4',  SUM(A.ORGDISTR_AMT))  DISTR_AMT4,  DECODE(B.PRNT_SEQ,  '5',  SUM(A.ORGDISTR_AMT))  DISTR_AMT5,  DECODE(B.PRNT_SEQ,  '6',  SUM(A.ORGDISTR_AMT))  DISTR_AMT6,  DECODE(B.PRNT_SEQ,  '7',  SUM(A.ORGDISTR_AMT))  DISTR_AMT7,  DECODE(B.PRNT_SEQ,  '8',  SUM(A.ORGDISTR_AMT))  DISTR_AMT8,  DECODE(B.PRNT_SEQ,  '9',  SUM(A.ORGDISTR_AMT))  DISTR_AMT9,  DECODE(B.PRNT_SEQ,  '10',  SUM(A.ORGDISTR_AMT))  DISTR_AMT10,  DECODE(B.PRNT_SEQ,  '11',  SUM(A.ORGDISTR_AMT))  DISTR_AMT11,  DECODE(B.PRNT_SEQ,  '12',  SUM(A.ORGDISTR_AMT))  DISTR_AMT12,  DECODE(B.PRNT_SEQ,  '13',  SUM(A.ORGDISTR_AMT))  DISTR_AMT13,  DECODE(B.PRNT_SEQ,  '14',  SUM(A.ORGDISTR_AMT))  DISTR_AMT14,  DECODE(B.PRNT_SEQ,  '15',  SUM(A.ORGDISTR_AMT))  DISTR_AMT15,  DECODE(B.PRNT_SEQ,  '16',  SUM(A.ORGDISTR_AMT))  DISTR_AMT16,  DECODE(B.PRNT_SEQ,  '17',  SUM(A.ORGDISTR_AMT))  DISTR_AMT17,  DECODE(B.PRNT_SEQ,  '18',  SUM(A.ORGDISTR_AMT))  DISTR_AMT18,  DECODE(B.PRNT_SEQ,  '19',  SUM(A.ORGDISTR_AMT))  DISTR_AMT19,  DECODE(B.PRNT_SEQ,  '20',  SUM(A.ORGDISTR_AMT))  DISTR_AMT20,  DECODE(B.PRNT_SEQ,  '21',  SUM(A.ORGDISTR_AMT))  DISTR_AMT21,  DECODE(B.PRNT_SEQ,  '22',  SUM(A.ORGDISTR_AMT))  DISTR_AMT22,  DECODE(B.PRNT_SEQ,  '23',  SUM(A.ORGDISTR_AMT))  DISTR_AMT23,  DECODE(B.PRNT_SEQ,  '24',  SUM(A.ORGDISTR_AMT))  DISTR_AMT24,  DECODE(B.PRNT_SEQ,  '25',  SUM(A.ORGDISTR_AMT))  DISTR_AMT25,  DECODE(B.PRNT_SEQ,  '26',  SUM(A.ORGDISTR_AMT))  DISTR_AMT26,  DECODE(B.PRNT_SEQ,  '27',  SUM(A.ORGDISTR_AMT))  DISTR_AMT27,  SUM(A.ATAX_AMT)  AS  ATAX_AMT,   \n";
        query +=" (SELECT  SUM(X.ORGDISTR_AMT)  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  X,  FIDU.TMEM_MB  Y  WHERE  X.MB_CD  =  Y.MB_CD(+)   \n";
        query +=" AND  X.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  Y.HOUSE_CD  IS  NOT  NULL   \n";
        query +=" AND  Y.MB_GBN1  =  'W'   \n";
        query +=" AND  Y.HOUSE_CD  <>  '082'  )  AS  DISTR_TOT,  0  ATAX_AMT1  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  A,  FIDU.TENV_AVECLASSCD  B,  FIDU.TMEM_MB  C  WHERE  A.MB_CD  =  C.MB_CD(+)   \n";
        query +=" AND  SUBSTR(A.MDM_CD,1,2)  =  B.AVECLASS_CD   \n";
        query +=" AND  A.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  C.MB_GBN1  =  'W'   \n";
        query +=" AND  C.HOUSE_CD  IS  NOT  NULL   \n";
        query +=" AND  C.HOUSE_CD  <>  '082'  GROUP  BY  B.PRNT_SEQ  UNION  ALL   \n";
        query +=" SELECT  '4'  AS  TRNSF_GBN,  '출판사'  AS  TRNSF_NM,   \n";
        query +=" (SELECT  COUNT(R.MB_CD)  AS  CNT  FROM  (   \n";
        query +=" SELECT  DISTINCT(A.MB_CD)  AS  MB_CD  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  A,  FIDU.TENV_AVECLASSCD  B  ,FIDU.TMEM_MB  C  WHERE  A.MB_CD  =  C.MB_CD(+)   \n";
        query +=" AND  SUBSTR(A.MDM_CD,1,2)  =  B.AVECLASS_CD   \n";
        query +=" AND  A.MB_CD  =  C.MB_CD(+)   \n";
        query +=" AND  A.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  C.MB_GBN1  IN  ('P','F'))  R  )  AS  CNT,  DECODE(B.PRNT_SEQ,  '1',  SUM(A.ORGDISTR_AMT))  DISTR_AMT1,  DECODE(B.PRNT_SEQ,  '2',  SUM(A.ORGDISTR_AMT))  DISTR_AMT2,  DECODE(B.PRNT_SEQ,  '3',  SUM(A.ORGDISTR_AMT))  DISTR_AMT3,  DECODE(B.PRNT_SEQ,  '4',  SUM(A.ORGDISTR_AMT))  DISTR_AMT4,  DECODE(B.PRNT_SEQ,  '5',  SUM(A.ORGDISTR_AMT))  DISTR_AMT5,  DECODE(B.PRNT_SEQ,  '6',  SUM(A.ORGDISTR_AMT))  DISTR_AMT6,  DECODE(B.PRNT_SEQ,  '7',  SUM(A.ORGDISTR_AMT))  DISTR_AMT7,  DECODE(B.PRNT_SEQ,  '8',  SUM(A.ORGDISTR_AMT))  DISTR_AMT8,  DECODE(B.PRNT_SEQ,  '9',  SUM(A.ORGDISTR_AMT))  DISTR_AMT9,  DECODE(B.PRNT_SEQ,  '10',  SUM(A.ORGDISTR_AMT))  DISTR_AMT10,  DECODE(B.PRNT_SEQ,  '11',  SUM(A.ORGDISTR_AMT))  DISTR_AMT11,  DECODE(B.PRNT_SEQ,  '12',  SUM(A.ORGDISTR_AMT))  DISTR_AMT12,  DECODE(B.PRNT_SEQ,  '13',  SUM(A.ORGDISTR_AMT))  DISTR_AMT13,  DECODE(B.PRNT_SEQ,  '14',  SUM(A.ORGDISTR_AMT))  DISTR_AMT14,  DECODE(B.PRNT_SEQ,  '15',  SUM(A.ORGDISTR_AMT))  DISTR_AMT15,  DECODE(B.PRNT_SEQ,  '16',  SUM(A.ORGDISTR_AMT))  DISTR_AMT16,  DECODE(B.PRNT_SEQ,  '17',  SUM(A.ORGDISTR_AMT))  DISTR_AMT17,  DECODE(B.PRNT_SEQ,  '18',  SUM(A.ORGDISTR_AMT))  DISTR_AMT18,  DECODE(B.PRNT_SEQ,  '19',  SUM(A.ORGDISTR_AMT))  DISTR_AMT19,  DECODE(B.PRNT_SEQ,  '20',  SUM(A.ORGDISTR_AMT))  DISTR_AMT20,  DECODE(B.PRNT_SEQ,  '21',  SUM(A.ORGDISTR_AMT))  DISTR_AMT21,  DECODE(B.PRNT_SEQ,  '22',  SUM(A.ORGDISTR_AMT))  DISTR_AMT22,  DECODE(B.PRNT_SEQ,  '23',  SUM(A.ORGDISTR_AMT))  DISTR_AMT23,  DECODE(B.PRNT_SEQ,  '24',  SUM(A.ORGDISTR_AMT))  DISTR_AMT24,  DECODE(B.PRNT_SEQ,  '25',  SUM(A.ORGDISTR_AMT))  DISTR_AMT25,  DECODE(B.PRNT_SEQ,  '26',  SUM(A.ORGDISTR_AMT))  DISTR_AMT26,  DECODE(B.PRNT_SEQ,  '27',  SUM(A.ORGDISTR_AMT))  DISTR_AMT27,  SUM(A.ATAX_AMT)  AS  ATAX_AMT,  (   \n";
        query +=" SELECT  SUM(X.ORGDISTR_AMT)  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  X,  FIDU.TMEM_MB  Y  WHERE  X.MB_CD  =  Y.MB_CD   \n";
        query +=" AND  X.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  Y.MB_GBN1  IN  ('P','F','B','C'  )  )  AS  DISTR_TOT,   \n";
        query +=" (SELECT  SUM(ATAX_AMT)  ATAX_AMT  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  A,  FIDU.TMEM_MB  B  WHERE  SUPP_YRMN  =:SUPP_YRMN   \n";
        query +=" AND  A.MB_CD  =  B.MB_CD   \n";
        query +=" AND  B.MB_GBN1  ='F'   \n";
        query +=" AND  NVL(FIDU.GET_FOR_ATAX_YN(MDM_CD),'0')  <>'1'  )  AS  ATAX_AMT1  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  A,  FIDU.TENV_AVECLASSCD  B,  FIDU.TMEM_MB  C  WHERE  SUBSTR(A.MDM_CD,1,2)  =  B.AVECLASS_CD   \n";
        query +=" AND  A.MB_CD  =  C.MB_CD(+)   \n";
        query +=" AND  A.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  C.MB_GBN1  IN  ('P','F','B','C'  )   \n";
        query +=" AND  C.MB_CD  <>  '10012619'  GROUP  BY  B.PRNT_SEQ  UNION  ALL   \n";
        query +=" SELECT  '5'  AS  TRNSF_GBN,  '권리단체  및  외국법인양수자'  AS  TRNSF_NM,   \n";
        query +=" (SELECT  COUNT(R.MB_CD)  AS  CNT  FROM  (   \n";
        query +=" SELECT  DISTINCT(A.MB_CD)  AS  MB_CD  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  A,  FIDU.TENV_AVECLASSCD  B  ,FIDU.TMEM_MB  C  WHERE  A.MB_CD  =  C.MB_CD(+)   \n";
        query +=" AND  SUBSTR(A.MDM_CD,1,2)  =  B.AVECLASS_CD   \n";
        query +=" AND  A.MB_CD  =  C.MB_CD(+)   \n";
        query +=" AND  A.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  (C.MB_GBN1  =  'U'   \n";
        query +=" OR  C.MB_CD  =  '10012619')  )  R  )  AS  CNT,  DECODE(B.PRNT_SEQ,  '1',  SUM(A.ORGDISTR_AMT))  DISTR_AMT1,  DECODE(B.PRNT_SEQ,  '2',  SUM(A.ORGDISTR_AMT))  DISTR_AMT2,  DECODE(B.PRNT_SEQ,  '3',  SUM(A.ORGDISTR_AMT))  DISTR_AMT3,  DECODE(B.PRNT_SEQ,  '4',  SUM(A.ORGDISTR_AMT))  DISTR_AMT4,  DECODE(B.PRNT_SEQ,  '5',  SUM(A.ORGDISTR_AMT))  DISTR_AMT5,  DECODE(B.PRNT_SEQ,  '6',  SUM(A.ORGDISTR_AMT))  DISTR_AMT6,  DECODE(B.PRNT_SEQ,  '7',  SUM(A.ORGDISTR_AMT))  DISTR_AMT7,  DECODE(B.PRNT_SEQ,  '8',  SUM(A.ORGDISTR_AMT))  DISTR_AMT8,  DECODE(B.PRNT_SEQ,  '9',  SUM(A.ORGDISTR_AMT))  DISTR_AMT9,  DECODE(B.PRNT_SEQ,  '10',  SUM(A.ORGDISTR_AMT))  DISTR_AMT10,  DECODE(B.PRNT_SEQ,  '11',  SUM(A.ORGDISTR_AMT))  DISTR_AMT11,  DECODE(B.PRNT_SEQ,  '12',  SUM(A.ORGDISTR_AMT))  DISTR_AMT12,  DECODE(B.PRNT_SEQ,  '13',  SUM(A.ORGDISTR_AMT))  DISTR_AMT13,  DECODE(B.PRNT_SEQ,  '14',  SUM(A.ORGDISTR_AMT))  DISTR_AMT14,  DECODE(B.PRNT_SEQ,  '15',  SUM(A.ORGDISTR_AMT))  DISTR_AMT15,  DECODE(B.PRNT_SEQ,  '16',  SUM(A.ORGDISTR_AMT))  DISTR_AMT16,  DECODE(B.PRNT_SEQ,  '17',  SUM(A.ORGDISTR_AMT))  DISTR_AMT17,  DECODE(B.PRNT_SEQ,  '18',  SUM(A.ORGDISTR_AMT))  DISTR_AMT18,  DECODE(B.PRNT_SEQ,  '19',  SUM(A.ORGDISTR_AMT))  DISTR_AMT19,  DECODE(B.PRNT_SEQ,  '20',  SUM(A.ORGDISTR_AMT))  DISTR_AMT20,  DECODE(B.PRNT_SEQ,  '21',  SUM(A.ORGDISTR_AMT))  DISTR_AMT21,  DECODE(B.PRNT_SEQ,  '22',  SUM(A.ORGDISTR_AMT))  DISTR_AMT22,  DECODE(B.PRNT_SEQ,  '23',  SUM(A.ORGDISTR_AMT))  DISTR_AMT23,  DECODE(B.PRNT_SEQ,  '24',  SUM(A.ORGDISTR_AMT))  DISTR_AMT24,  DECODE(B.PRNT_SEQ,  '25',  SUM(A.ORGDISTR_AMT))  DISTR_AMT25,  DECODE(B.PRNT_SEQ,  '26',  SUM(A.ORGDISTR_AMT))  DISTR_AMT26,  DECODE(B.PRNT_SEQ,  '27',  SUM(A.ORGDISTR_AMT))  DISTR_AMT27,  SUM(A.ATAX_AMT)  AS  ATAX_AMT,  (   \n";
        query +=" SELECT  SUM(X.ORGDISTR_AMT)  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  X,  FIDU.TMEM_MB  Y  WHERE  X.MB_CD  =  Y.MB_CD   \n";
        query +=" AND  X.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  Y.MB_GBN1  =  'U'  )  AS  DISTR_TOT,  0  ATAX_AMT1  FROM  FIDU.TTAC_MDMCLASSSUPPAMT  A,  FIDU.TENV_AVECLASSCD  B,  FIDU.TMEM_MB  C  WHERE  SUBSTR(A.MDM_CD,1,2)  =  B.AVECLASS_CD   \n";
        query +=" AND  A.MB_CD  =  C.MB_CD(+)   \n";
        query +=" AND  A.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  (C.MB_GBN1  =  'U'   \n";
        query +=" OR  C.MB_CD  =  '10012619')  GROUP  BY  B.PRNT_SEQ  )Z  GROUP  BY  Z.TRNSF_GBN,  Z.TRNSF_NM  )C,  (   \n";
        query +=" SELECT  X.TRNSF_GBN,  TRNSF_NM,  SUM(X.DISTR_AMT28)  AS  DISTR_AMT28,  SUM(X.DISTR_AMT29)  AS  DISTR_AMT29,  SUM(X.DISTR_AMT30)  AS  DISTR_AMT30,  SUM(X.DISTR_AMT31)  AS  DISTR_AMT31,  SUM(X.DISTR_AMT32)  AS  DISTR_AMT32,  SUM(X.DISTR_AMT33)  AS  DISTR_AMT33,  SUM(X.DISTR_AMT34)  AS  DISTR_AMT34,  SUM(X.DISTR_AMT35)  AS  DISTR_AMT35,  SUM(X.DISTR_AMT36)  AS  DISTR_AMT36,  SUM(X.DISTR_AMT37)  AS  DISTR_AMT37,  SUM(X.DISTR_AMT38)  AS  DISTR_AMT38,  SUM(X.DISTR_AMT39)  AS  DISTR_AMT39,  SUM(X.DISTR_AMT40)  AS  DISTR_AMT40,  SUM(X.DISTR_AMT41)  AS  DISTR_AMT41,  SUM(X.DISTR_AMT42)  AS  DISTR_AMT42,  SUM(X.DISTR_AMT43)  AS  DISTR_AMT43,  SUM(X.DISTR_AMT44)  AS  DISTR_AMT44,  SUM(X.DISTR_AMT45)  AS  DISTR_AMT45,  SUM(X.DISTR_AMT46)  AS  DISTR_AMT46,  SUM(NVL(X.DISTR_AMT28,0))+  SUM(NVL(X.DISTR_AMT29,0))+  SUM(NVL(X.DISTR_AMT30,0))+  SUM(NVL(X.DISTR_AMT31,0))+  SUM(NVL(X.DISTR_AMT32,0))+  SUM(NVL(X.DISTR_AMT33,0))+  SUM(NVL(X.DISTR_AMT34,0))+  SUM(NVL(X.DISTR_AMT35,0))+  SUM(NVL(X.DISTR_AMT36,0))+  SUM(NVL(X.DISTR_AMT37,0))+  SUM(NVL(X.DISTR_AMT38,0))+  SUM(NVL(X.DISTR_AMT39,0))+  SUM(NVL(X.DISTR_AMT40,0))+  SUM(NVL(X.DISTR_AMT41,0))+  SUM(NVL(X.DISTR_AMT42,0))+  SUM(NVL(X.DISTR_AMT43,0))+  SUM(NVL(X.DISTR_AMT44,0))+  SUM(NVL(X.DISTR_AMT45,0))+  SUM(NVL(X.DISTR_AMT46,0))  AS  DISTR_GTOT  FROM  (   \n";
        query +=" SELECT  D.TRNSF_GBN,  '원작'  AS  TRNSF_NM,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '01',  DEDCT_AMT))  DISTR_AMT28,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '02',  DEDCT_AMT))  DISTR_AMT29,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '03',  DEDCT_AMT))  DISTR_AMT30,  0  AS  DISTR_AMT31,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '04',  DEDCT_AMT))  DISTR_AMT32,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '05',  DEDCT_AMT))  DISTR_AMT33,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '06',  DEDCT_AMT))  DISTR_AMT34,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '07',  DEDCT_AMT))  DISTR_AMT35,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '01',  DEDCT_AMT))  DISTR_AMT36,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '02',  DEDCT_AMT))  DISTR_AMT37,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '03',  DEDCT_AMT))  DISTR_AMT38,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '04',  DEDCT_AMT))  DISTR_AMT39,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '05',  DEDCT_AMT))  DISTR_AMT40,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '06',  DEDCT_AMT))  DISTR_AMT41,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '10',  DEDCT_AMT))  DISTR_AMT42,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '11',  DEDCT_AMT))  DISTR_AMT43,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '08',  DEDCT_AMT))  DISTR_AMT44,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '09',  DEDCT_AMT))  DISTR_AMT45,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '12',  DEDCT_AMT))  DISTR_AMT46  FROM  FIDU.TTAC_DEDCTAMT  D,  FIDU.TMEM_MB  E  WHERE  D.MB_CD  =  E.MB_CD(+)   \n";
        query +=" AND  D.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  D.TRNSF_GBN  =  '1'   \n";
        query +=" AND  E.MB_GBN1  =  'W'   \n";
        query +=" AND  (E.HOUSE_CD  IS  NULL   \n";
        query +=" OR  E.HOUSE_CD  ='082')  UNION  ALL   \n";
        query +=" SELECT  D.TRNSF_GBN,  '승계.양수'  AS  TRNSF_NM,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '01',  DEDCT_AMT))  DISTR_AMT28,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '02',  DEDCT_AMT))  DISTR_AMT29,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '03',  DEDCT_AMT))  DISTR_AMT30,  0  AS  DISTR_AMT31,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '04',  DEDCT_AMT))  DISTR_AMT32,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '05',  DEDCT_AMT))  DISTR_AMT33,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '06',  DEDCT_AMT))  DISTR_AMT34,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '07',  DEDCT_AMT))  DISTR_AMT35,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '01',  DEDCT_AMT))  DISTR_AMT36,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '02',  DEDCT_AMT))  DISTR_AMT37,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '03',  DEDCT_AMT))  DISTR_AMT38,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '04',  DEDCT_AMT))  DISTR_AMT39,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '05',  DEDCT_AMT))  DISTR_AMT40,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '06',  DEDCT_AMT))  DISTR_AMT41,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '10',  DEDCT_AMT))  DISTR_AMT42,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '11',  DEDCT_AMT))  DISTR_AMT43,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '08',  DEDCT_AMT))  DISTR_AMT44,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '09',  DEDCT_AMT))  DISTR_AMT45,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '12',  DEDCT_AMT))  DISTR_AMT46  FROM  FIDU.TTAC_DEDCTAMT  D,  FIDU.TMEM_MB  E  WHERE  D.MB_CD  =  E.MB_CD(+)   \n";
        query +=" AND  D.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  D.TRNSF_GBN  =  '2'   \n";
        query +=" AND  E.MB_GBN1  =  'W'   \n";
        query +=" AND  (E.HOUSE_CD  IS  NULL   \n";
        query +=" OR  E.HOUSE_CD  ='082')  UNION  ALL   \n";
        query +=" SELECT  '3'  AS  TRNSF_GBN,  '외국'  AS  TRNSF_NM,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '01',  DEDCT_AMT))  DISTR_AMT28,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '02',  DEDCT_AMT))  DISTR_AMT29,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '03',  DEDCT_AMT))  DISTR_AMT30,  0  AS  DISTR_AMT31,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '04',  DEDCT_AMT))  DISTR_AMT32,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '05',  DEDCT_AMT))  DISTR_AMT33,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '06',  DEDCT_AMT))  DISTR_AMT34,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '07',  DEDCT_AMT))  DISTR_AMT35,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '01',  DEDCT_AMT))  DISTR_AMT36,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '02',  DEDCT_AMT))  DISTR_AMT37,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '03',  DEDCT_AMT))  DISTR_AMT38,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '04',  DEDCT_AMT))  DISTR_AMT39,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '05',  DEDCT_AMT))  DISTR_AMT40,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '06',  DEDCT_AMT))  DISTR_AMT41,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '10',  DEDCT_AMT))  DISTR_AMT42,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '11',  DEDCT_AMT))  DISTR_AMT43,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '08',  DEDCT_AMT))  DISTR_AMT44,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '09',  DEDCT_AMT))  DISTR_AMT45,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '12',  DEDCT_AMT))  DISTR_AMT46  FROM  FIDU.TTAC_DEDCTAMT  D,  FIDU.TMEM_MB  E  WHERE  D.MB_CD  =  E.MB_CD(+)   \n";
        query +=" AND  D.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  E.MB_GBN1  =  'W'   \n";
        query +=" AND  (E.HOUSE_CD  <>  '082'   \n";
        query +=" AND  E.HOUSE_CD  IS  NOT  NULL)  UNION  ALL   \n";
        query +=" SELECT  '4'  AS  TRNSF_GBN,  '출판사'  AS  TRNSF_NM,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '01',  DEDCT_AMT))  DISTR_AMT28,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '02',  DEDCT_AMT))  DISTR_AMT29,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '03',  DEDCT_AMT))  DISTR_AMT30,  0  AS  DISTR_AMT31,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '04',  DEDCT_AMT))  DISTR_AMT32,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '05',  DEDCT_AMT))  DISTR_AMT33,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '06',  DEDCT_AMT))  DISTR_AMT34,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '07',  DEDCT_AMT))  DISTR_AMT35,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '01',  DEDCT_AMT))  DISTR_AMT36,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '02',  DEDCT_AMT))  DISTR_AMT37,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '03',  DEDCT_AMT))  DISTR_AMT38,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '04',  DEDCT_AMT))  DISTR_AMT39,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '05',  DEDCT_AMT))  DISTR_AMT40,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '06',  DEDCT_AMT))  DISTR_AMT41,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '10',  DEDCT_AMT))  DISTR_AMT42,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '11',  DEDCT_AMT))  DISTR_AMT43,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '08',  DEDCT_AMT))  DISTR_AMT44,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '09',  DEDCT_AMT))  DISTR_AMT45,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '12',  DEDCT_AMT))  DISTR_AMT46  FROM  FIDU.TTAC_DEDCTAMT  D,  FIDU.TMEM_MB  E  WHERE  D.MB_CD  =  E.MB_CD(+)   \n";
        query +=" AND  D.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  E.MB_GBN1  IN  ('P','F','B','C'  )   \n";
        query +=" AND  E.MB_CD  <>  '10012619'  UNION  ALL   \n";
        query +=" SELECT  '5'  AS  TRNSF_GBN,  '권리단체  및  외국법인양수자'  AS  TRNSF_NM,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '01',  DEDCT_AMT))  DISTR_AMT28,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '02',  DEDCT_AMT))  DISTR_AMT29,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '03',  DEDCT_AMT))  DISTR_AMT30,  0  AS  DISTR_AMT31,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '04',  DEDCT_AMT))  DISTR_AMT32,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '05',  DEDCT_AMT))  DISTR_AMT33,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '06',  DEDCT_AMT))  DISTR_AMT34,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '07',  DEDCT_AMT))  DISTR_AMT35,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '01',  DEDCT_AMT))  DISTR_AMT36,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '02',  DEDCT_AMT))  DISTR_AMT37,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '03',  DEDCT_AMT))  DISTR_AMT38,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '04',  DEDCT_AMT))  DISTR_AMT39,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '05',  DEDCT_AMT))  DISTR_AMT40,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '06',  DEDCT_AMT))  DISTR_AMT41,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '10',  DEDCT_AMT))  DISTR_AMT42,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '11',  DEDCT_AMT))  DISTR_AMT43,  DECODE(D.DEDCT_GBNONE,  '01',  DECODE(D.DEDCT_GBNTWO,  '08',  DEDCT_AMT))  DISTR_AMT44,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '09',  DEDCT_AMT))  DISTR_AMT45,  DECODE(D.DEDCT_GBNONE,  '02',  DECODE(D.DEDCT_GBNTWO,  '12',  DEDCT_AMT))  DISTR_AMT46  FROM  FIDU.TTAC_DEDCTAMT  D,  FIDU.TMEM_MB  E  WHERE  D.MB_CD  =  E.MB_CD(+)   \n";
        query +=" AND  D.SUPP_YRMN  =  SUBSTR(:SUPP_YRMN,1,6)   \n";
        query +=" AND  (E.MB_GBN1  =  'U'   \n";
        query +=" OR  E.MB_CD  =  '10012619')  )X  GROUP  BY  X.TRNSF_GBN,  X.TRNSF_NM  )D,  (   \n";
        query +=" SELECT  MAX(X.DISTR_TAMT1  )  DISTR_TAMT1  ,  MAX(X.DISTR_TAMT2  )  DISTR_TAMT2  ,  MAX(X.DISTR_TAMT3  )  DISTR_TAMT3  ,  MAX(X.DISTR_TAMT4  )  DISTR_TAMT4  ,  MAX(X.DISTR_TAMT5  )  DISTR_TAMT5  ,  MAX(X.DISTR_TAMT6  )  DISTR_TAMT6  ,  MAX(X.DISTR_TAMT7  )  DISTR_TAMT7  ,  MAX(X.DISTR_TAMT8  )  DISTR_TAMT8  ,  MAX(X.DISTR_TAMT9  )  DISTR_TAMT9  ,  MAX(X.DISTR_TAMT10)  DISTR_TAMT10,  MAX(X.DISTR_TAMT11)  DISTR_TAMT11,  MAX(X.DISTR_TAMT12)  DISTR_TAMT12,  MAX(X.DISTR_TAMT13)  DISTR_TAMT13,  MAX(X.DISTR_TAMT14)  DISTR_TAMT14,  MAX(X.DISTR_TAMT15)  DISTR_TAMT15,  MAX(X.DISTR_TAMT16)  DISTR_TAMT16,  MAX(X.DISTR_TAMT17)  DISTR_TAMT17,  MAX(X.DISTR_TAMT18)  DISTR_TAMT18,  MAX(X.DISTR_TAMT19)  DISTR_TAMT19,  MAX(X.DISTR_TAMT20)  DISTR_TAMT20,  MAX(X.DISTR_TAMT21)  DISTR_TAMT21,  MAX(X.DISTR_TAMT22)  DISTR_TAMT22,  MAX(X.DISTR_TAMT23)  DISTR_TAMT23,  MAX(X.DISTR_TAMT24)  DISTR_TAMT24,  MAX(X.DISTR_TAMT25)  DISTR_TAMT25,  MAX(X.DISTR_TAMT26)  DISTR_TAMT26,  MAX(X.DISTR_TAMT27)  DISTR_TAMT27  FROM  (   \n";
        query +=" SELECT  NVL(  DECODE(PRNT_SEQ,  '1',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT1,  NVL(  DECODE(PRNT_SEQ,  '2',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT2,  NVL(  DECODE(PRNT_SEQ,  '3',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT3,  NVL(  DECODE(PRNT_SEQ,  '4',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT4,  NVL(  DECODE(PRNT_SEQ,  '5',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT5,  NVL(  DECODE(PRNT_SEQ,  '6',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT6,  NVL(  DECODE(PRNT_SEQ,  '7',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT7,  NVL(  DECODE(PRNT_SEQ,  '8',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT8,  NVL(  DECODE(PRNT_SEQ,  '9',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT9,  NVL(  DECODE(PRNT_SEQ,  '10',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT10,  NVL(  DECODE(PRNT_SEQ,  '11',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT11,  NVL(  DECODE(PRNT_SEQ,  '12',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT12,  NVL(  DECODE(PRNT_SEQ,  '13',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT13,  NVL(  DECODE(PRNT_SEQ,  '14',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT14,  NVL(  DECODE(PRNT_SEQ,  '15',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT15,  NVL(  DECODE(PRNT_SEQ,  '16',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT16,  NVL(  DECODE(PRNT_SEQ,  '17',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT17,  NVL(  DECODE(PRNT_SEQ,  '18',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT18,  NVL(  DECODE(PRNT_SEQ,  '19',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT19,  NVL(  DECODE(PRNT_SEQ,  '20',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT20,  NVL(  DECODE(PRNT_SEQ,  '21',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT21,  NVL(  DECODE(PRNT_SEQ,  '22',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT22,  NVL(  DECODE(PRNT_SEQ,  '23',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT23,  NVL(  DECODE(PRNT_SEQ,  '24',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT24,  NVL(  DECODE(PRNT_SEQ,  '25',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT25,  NVL(  DECODE(PRNT_SEQ,  '26',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT26,  NVL(  DECODE(PRNT_SEQ,  '27',  AVECLASS_CD_NM),  '')  AS  DISTR_TAMT27  FROM  FIDU.TENV_AVECLASSCD  )  X  )  E,  (   \n";
        query +=" SELECT  MAX(DISTR_TAMT28)  DISTR_TAMT28,  MAX(DISTR_TAMT29)  DISTR_TAMT29,  MAX(DISTR_TAMT30)  DISTR_TAMT30,  MAX(DISTR_TAMT31)  DISTR_TAMT31,  MAX(DISTR_TAMT32)  DISTR_TAMT32,  MAX(DISTR_TAMT33)  DISTR_TAMT33,  MAX(DISTR_TAMT34)  DISTR_TAMT34,  MAX(DISTR_TAMT35)  DISTR_TAMT35,  MAX(DISTR_TAMT36)  DISTR_TAMT36,  MAX(DISTR_TAMT37)  DISTR_TAMT37,  MAX(DISTR_TAMT38)  DISTR_TAMT38,  MAX(DISTR_TAMT39)  DISTR_TAMT39,  MAX(DISTR_TAMT40)  DISTR_TAMT40,  MAX(DISTR_TAMT41)  DISTR_TAMT41,  MAX(DISTR_TAMT42)  DISTR_TAMT42,  MAX(DISTR_TAMT43)  DISTR_TAMT43,  MAX(DISTR_TAMT44)  DISTR_TAMT44,  MAX(DISTR_TAMT45)  DISTR_TAMT45,  MAX(DISTR_TAMT46)  DISTR_TAMT46  FROM  (   \n";
        query +=" SELECT  '1'  AS  RW  ,  A.HIGH_CD  HIGH_CD,  B.HIGH_CD  HIGH_CD2,  DECODE(A.CODE_CD,  '01',  A.CODE_NM)  DISTR_TAMT28,  DECODE(A.CODE_CD,  '02',  A.CODE_NM)  DISTR_TAMT29,  DECODE(A.CODE_CD,  '03',  A.CODE_NM)  DISTR_TAMT30,  '부가가치세'  DISTR_TAMT31,  DECODE(A.CODE_CD,  '04',  A.CODE_NM)  DISTR_TAMT32,  DECODE(A.CODE_CD,  '05',  A.CODE_NM)  DISTR_TAMT33,  DECODE(A.CODE_CD,  '06',  A.CODE_NM)  DISTR_TAMT34,  DECODE(A.CODE_CD,  '07',  A.CODE_NM)  DISTR_TAMT35,  DECODE(B.CODE_CD,  '01',  B.CODE_NM)  DISTR_TAMT36,  DECODE(B.CODE_CD,  '02',  B.CODE_NM)  DISTR_TAMT37,  DECODE(B.CODE_CD,  '03',  B.CODE_NM)  DISTR_TAMT38,  DECODE(B.CODE_CD,  '04',  B.CODE_NM)  DISTR_TAMT39,  DECODE(B.CODE_CD,  '05',  B.CODE_NM)  DISTR_TAMT40,  DECODE(B.CODE_CD,  '06',  B.CODE_NM)  DISTR_TAMT41,  DECODE(B.CODE_CD,  '10',  B.CODE_NM)  DISTR_TAMT42,  DECODE(B.CODE_CD,  '11',  B.CODE_NM)  DISTR_TAMT43,  DECODE(A.CODE_CD,  '08',  A.CODE_NM)  DISTR_TAMT44,  DECODE(B.CODE_CD,  '09',  B.CODE_NM)  DISTR_TAMT45,  DECODE(B.CODE_CD,  '12',  B.CODE_NM)  DISTR_TAMT46  FROM  FIDU.TENV_CODE  A,  FIDU.TENV_CODE  B  WHERE  A.HIGH_CD  =  '00254'   \n";
        query +=" AND  B.HIGH_CD  =  '00040'  )X  GROUP  BY  HIGH_CD,  HIGH_CD2  )F  WHERE  C.TRNSF_NM  =  D.TRNSF_NM   \n";
        query +=" AND  C.TRNSF_GBN  =  D.TRNSF_GBN  ORDER  BY  C.TRNSF_GBN,  C.TRNSF_NM ";
        sobj.setSql(query);
        sobj.setString("SUPP_YRMN", SUPP_YRMN);               //지급 년월
        return sobj;
    }
    //##**$$searchTest
    //##**$$end
}
